{{- if not (eq .Storage.Backend "local") }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dind-volume-cleanup-{{ .AppName }}
  namespace: {{ .Namespace }}
  labels:
    app: dind-volume-cleanup
spec:
  schedule: "0,10,20,30,40,50 * * * *"
  concurrencyPolicy: Forbid
  {{- if eq .Storage.Backend "local" }}
  suspend: true
  {{- end }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: volume-provisioner-{{ .AppName }}
          restartPolicy: Never
          containers:
            - name: dind-volume-cleanup
              image: {{ if ne .DockerRegistry ""}} {{- .DockerRegistry }}/{{ .Storage.VolumeCleaner.Image.Name }}:{{ .Storage.VolumeCleaner.Image.Tag }} {{- else }}{{- .Storage.VolumeCleaner.Image.Name }}:{{ .Storage.VolumeCleaner.Image.Tag }} {{- end}}
              env:
              - name: PROVISIONED_BY
                value: codefresh.io/dind-volume-provisioner-{{ .AppName }}-{{ .Namespace }}
          securityContext:
            fsGroup: 3000
            runAsGroup: 3000
            runAsUser: 3000
{{- end }}