{{- if .CreateRbac }}
{{- if and .Monitor.Enabled .Monitor.RbacEnabled }}
{{- if .Monitor.UseNamespaceWithRole }}
kind: RoleBinding
{{- else }}
kind: ClusterRoleBinding
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Monitor.AppName }}-cluster-reader
  namespace: {{ .Namespace }}
  labels:
    app: {{ .Monitor.AppName }}
    version: {{ .Version }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Namespace }}
  name: {{ .Monitor.AppName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  {{- if .Monitor.UseNamespaceWithRole }}
  kind: Role
  {{- else }}
  kind: ClusterRole
  {{- end }}
  name: {{ .Monitor.AppName }}-cluster-reader
{{- end }}
{{- end }}