{{- if .CreateRbac }}
{{- if .Monitor.RbacEnabled }}
{{- if .Monitor.UseNamespaceWithRole }}
kind: RoleBinding
{{- else }}
kind: ClusterRoleBinding
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Monitor.AppName }}-rollback
  namespace: {{ .Namespace }}
  labels:
    app: {{ .Monitor.AppName }}
    version: {{ .Version }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Namespace }}
    name: {{ .Monitor.AppName }}-rollback
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
  {{- end }}
{{- end }}