{{- if .CreateRbac }}
{{- if and .Monitor.Enabled .Monitor.RbacEnabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Monitor.AppName }}
  namespace: {{ .Namespace }}
  annotations:
  {{ range $key, $value := .Monitor.ServiceAccount.Annotations }}
    {{ $key }}: {{ $value }}
  {{ end }}
  labels:
    app: {{ .Monitor.AppName }}
    version: {{ .Version }}
{{- end }}
{{- end }}
