{{- if .CreateRbac }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Runtime.EngineAppName }}
  namespace: {{ .Namespace }}
  annotations:
  {{ range $key, $value := .Runtime.ServiceAccount.Annotations }}
    {{ $key }}: {{ $value }}
  {{ end }}
  labels:
    app: {{ .AppProxy.AppName }}
    version: {{ .Version }}
{{- end }}
