{{- if .CreateRbac }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: volume-provisioner-{{ .AppName }}
  namespace: {{ .Namespace }}
  annotations:
  {{ range $key, $value := .Storage.VolumeProvisioner.ServiceAccount.Annotations }}
    {{ $key }}: {{ $value }}
  {{ end }}
  labels:
    app: dind-volume-provisioner
{{- end }}