// Code generated by go generate; DO NOT EDIT.
// using data from templates/kubernetes
package kubernetes

func TemplatesMap() map[string]string {
	templatesMap := make(map[string]string)

	templatesMap["cluster-role-binding.dind-volume-provisioner.vp.yaml"] = `---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: volume-provisioner-{{ .AppName }}-{{ .Namespace }}
  labels:
    app: dind-volume-provisioner-{{ .AppName }}
subjects:
  - kind: ServiceAccount
    name: volume-provisioner-{{ .AppName }}
    namespace: {{ .Namespace }}
roleRef:
  kind: ClusterRole
  name: volume-provisioner-{{ .AppName }}-{{ .Namespace }}
  apiGroup: rbac.authorization.k8s.io
`

	templatesMap["cluster-role-binding.engine.yaml"] = `kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .AppName }}-{{ .Namespace }}-engine
subjects:
- kind: ServiceAccount
  name: engine
  namespace: {{ .Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io`

	templatesMap["cluster-role-binding.venona.yaml"] = `kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .AppName }}-{{ .Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .AppName }}
  namespace: {{ .Namespace }}
roleRef:
  kind: ClusterRole
  name: system:discovery
  apiGroup: rbac.authorization.k8s.io`

	templatesMap["cluster-role.dind-volume-provisioner.vp.yaml"] = `kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: volume-provisioner-{{ .AppName }}-{{ .Namespace }}
  labels:
    app: dind-volume-provisioner
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
`

	templatesMap["cluster-role.engine.yaml"] = `kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .AppName }}-{{ .Namespace }}-engine
rules:
  - apiGroups: [""]
    resources: ["pods", "persistentvolumeclaims"]
    verbs: ["get", "create", "delete", "list"]
`

	templatesMap["codefresh-certs-server-secret.re.yaml"] = `apiVersion: v1
type: Opaque
kind: Secret
metadata:
  labels:
    app: venona
  name: codefresh-certs-server
  namespace: {{ .Namespace }}
data:
  server-cert.pem: {{ .ServerCert.Cert }}
  server-key.pem: {{ .ServerCert.Key }}
  ca.pem: {{ .ServerCert.Ca }}

`

	templatesMap["cron-job.dind-volume-cleanup.vp.yaml"] = `{{- if not (eq .Storage.Backend "local") }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dind-volume-cleanup-{{ .AppName }}
  namespace: {{ .Namespace }}
  labels:
    app: dind-volume-cleanup
spec:
  schedule: "0,10,20,30,40,50 * * * *"
  concurrencyPolicy: Forbid
  {{- if eq .Storage.Backend "local" }}
  suspend: true
  {{- end }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: volume-provisioner-{{ .AppName }}
          restartPolicy: Never
          containers:
            - name: dind-volume-cleanup
              image: codefresh/dind-volume-cleanup
              env:
              - name: PROVISIONED_BY
                value: codefresh.io/dind-volume-provisioner-{{ .AppName }}-{{ .Namespace }}
{{- end }}`

	templatesMap["daemonset.dind-lv-monitor.vp.yaml"] = `{{- if eq .Storage.Backend "local" -}}
{{- $localVolumeParentDir := ( .Storage.LocalVolumeParentDir | default "/var/lib/codefresh/dind-volumes" ) }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dind-lv-monitor-{{ .AppName }}
  namespace: {{ .Namespace }}
  labels:
    app: dind-lv-monitor
spec:
  selector:
    matchLabels:
      app: dind-lv-monitor
  template:
    metadata:
      labels:
        app: dind-lv-monitor
      annotations:
        prometheus_port: "9100"
        prometheus_scrape: "true"
    spec:
      serviceAccountName: volume-provisioner-{{ .AppName }}
      # Debug:
      # hostNetwork: true
      # nodeSelector:
      #   kubernetes.io/role: "node"
      tolerations:
        - key: 'codefresh/dind'
          operator: 'Exists'
          effect: 'NoSchedule'
      {{ if ne .Tolerations "" }}
        {{ .Tolerations | indent 8 }}
      {{ end }}
      containers:
        - image: codefresh/dind-volume-utils:v5
          name: lv-cleaner
          imagePullPolicy: Always
          command:
          - /bin/local-volumes-agent
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: VOLUME_PARENT_DIR
              value: {{ $localVolumeParentDir }}
#              Debug:
#            - name: DRY_RUN
#              value: "1"
#            - name: DEBUG
#              value: "1"
#            - name: SLEEP_INTERVAL
#              value: "3"
#            - name: LOG_DF_EVERY
#              value: "60"
#            - name: KB_USAGE_THRESHOLD
#              value: "20"

          volumeMounts:
          - mountPath: {{ $localVolumeParentDir }}
            readOnly: false
            name: dind-volume-dir
      volumes:
      - name: dind-volume-dir
        hostPath:
          path: {{ $localVolumeParentDir }}
{{- end -}}`

	templatesMap["deployment.dind-volume-provisioner.vp.yaml"] = `apiVersion: apps/v1
kind: Deployment
metadata:
  name: dind-volume-provisioner-{{ .AppName }}
  namespace: {{ .Namespace }}
  labels:
    app: dind-volume-provisioner
spec:
  selector:
    matchLabels:
      app: dind-volume-provisioner
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dind-volume-provisioner
    spec:
      {{ if .Storage.VolumeProvisioner.NodeSelector }}
      nodeSelector: 
{{ .Storage.VolumeProvisioner.NodeSelector | nodeSelectorParamToYaml | indent 8 | unescape}}
      {{ end }}
      serviceAccount: volume-provisioner-{{ .AppName }}
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: "Exists"
      {{ if ne .Tolerations "" }}
        {{ .Tolerations | indent 6 }}
      {{ end }}
      containers:
      - name: dind-volume-provisioner
        image: {{ .Storage.VolumeProvisioner.Image }}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "200m"
            memory: "200Mi"
          limits:
            cpu: "1000m"
            memory: "6000Mi"
        command:
          - /usr/local/bin/dind-volume-provisioner
          - -v=4
          - --resync-period=50s
        env:
        - name: PROVISIONER_NAME
          value: codefresh.io/dind-volume-provisioner-{{ .AppName }}-{{ .Namespace }}
        {{- if .Storage.AwsAccessKeyId }}
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: dind-volume-provisioner-{{ .AppName }}
              key: aws_access_key_id
        {{- end }}
        {{- if .Storage.AwsSecretAccessKey }}
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: dind-volume-provisioner-{{ .AppName }}
              key: aws_secret_access_key
        {{- end }}
      {{- if .Storage.GoogleServiceAccount }}
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/dind-volume-provisioner/credentials/google-service-account.json
        volumeMounts:
        - name: credentials
          readOnly: true
          mountPath: "/etc/dind-volume-provisioner/credentials"
      volumes:
      - name: credentials
        secret:
          secretName: dind-volume-provisioner-{{ .AppName }}
      {{- end }}
`

	templatesMap["deployment.k8sagent.yaml"] = `apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .AppName }}
  namespace: {{ .Namespace }}
  labels:
    app: {{ .AppName }}
    version: {{ .Version }}
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  selector:
    matchLabels:
      app: {{ .AppName }}
  template:
    metadata:
      labels:
        app: {{ .AppName }}
        version: {{ .Version }}
    spec:
      {{- if .Values.rbacEnabled}}
      serviceAccountName: {{ .Release.Name  | quote }}
      {{- end }}
      containers:
      - name: {{ .AppName }}
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: Always
        env:
          - name: SERVICE_NAME
            value: {{ .AppName }}
          - name: NAMESPACE_INTERVAL
            value: {{ .Values.namespaceInterval | quote }}
          - name: POD_INTERVAL
            value: {{ .Values.podInterval | quote }}
          - name: DEPLOYMENT_INTERVAL
            value: {{ .Values.deploymentInterval | quote }}
          - name: RELEASE_INTERVAL
            value: {{ .Values.releaseInterval | quote }}
          - name: SERVICE_INTERVAL
            value: {{ .Values.serviceInterval | quote }}
          - name: SECRET_INTERVAL
            value: {{ .Values.secretInterval | quote }}
          {{- if .Values.useNamespaceWideRole }}
          - name: ROLE_BINDING
            value: "true"
          {{- end }}
          - name: PORT
            value: "9020"
          - name: CLUSTER_URL
            value: {{ .Values.clusterUrl | quote }}
          - name: CLUSTER_TOKEN
            value: {{ .Values.clusterToken | quote }}
          - name: CLUSTER_CA
            value: {{ .Values.clusterCA | quote }}
          - name: API_TOKEN
            value: {{ .Values.apiToken | quote }}
          - name: CLUSTER_ID
            value: {{ .Values.clusterId | quote }}
          - name: API_URL
            value: {{ .Values.apiUrl | quote }}
          - name: ACCOUNT_ID
            value: {{ .Values.accountId | quote }}
          - name: DISABLE_HELM
            value: {{ .Values.disableHelm | quote }}
          - name: HELM3
            value: {{ .Values.helm3 | quote }}
          - name: CLEAN
            value: "{{ .Values.clean }}"
          - name: NAMESPACE
            value: "{{ .Namespace }}"
          - name: NODE_OPTIONS
            value: "--max_old_space_size={{ .Values.heapSize }}"
          - name: FORCE_DISABLE_HELM_RELEASES
            value: "{{ .Values.forceDisableHelmReleases }}"
        ports:
        - containerPort: 9020
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /api/ping
            port: 9020
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
`

	templatesMap["deployment.venona.yaml"] = `apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .AppName }}
    version: {{ .Version }} 
  name: {{ .AppName }}
  namespace: {{ .Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .AppName }}
      version: {{ .Version }}
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .AppName }}
        version: {{ .Version }}
    spec:
      volumes:
        - name: venonaconf
          secret:
            secretName: venonaconf
      {{ if ne .NodeSelector "" }}
      nodeSelector:
        {{ .NodeSelector }}
      {{ end }}
      {{ if ne .Tolerations "" }}
      tolerations:
        {{ .Tolerations | indent 8 }}
      {{ end }}
      containers:
      - env:
        - name: SELF_DEPLOYMENT_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CODEFRESH_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .AppName }}
              key: codefresh.token
        - name: CODEFRESH_HOST
          value: {{ .CodefreshHost }}
        - name: AGENT_MODE
          value: {{ .Mode }}
        - name: AGENT_NAME
          value: {{ .AppName }}
        - name: AGENT_ID
          value: {{ .AgentId }}
        - name: VENONA_CONFIG_DIR
          value: "/etc/secrets"
        image: {{ .Image.Name }}:{{ .Image.Tag }}
        volumeMounts:
        - name: venonaconf
          mountPath: "/etc/secrets"
          readOnly: true
        imagePullPolicy: Always
        name: {{ .AppName }}
      restartPolicy: Always
`

	templatesMap["dind-daemon-conf.re.yaml"] = `---
apiVersion: v1
kind: ConfigMap
metadata:
  name: codefresh-dind-config
  namespace: {{ .Namespace }}
data:
  daemon.json: |
    {
      "hosts": [ "unix:///var/run/docker.sock",
                 "tcp://0.0.0.0:1300"],
      "storage-driver": "overlay2",
      "tlsverify": true,  
      "tls": true,
      "tlscacert": "/etc/ssl/cf-client/ca.pem",
      "tlscert": "/etc/ssl/cf/server-cert.pem",
      "tlskey": "/etc/ssl/cf/server-key.pem",
      "insecure-registries" : ["192.168.99.100:5000"],
      "metrics-addr" : "0.0.0.0:9323",
      "experimental" : true
    }
`

	templatesMap["dind-headless-service.re.yaml"] = `---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dind
  name: dind
  namespace: {{ .Namespace }}
spec:
  ports:
  - name: "dind-port"
    port: 1300
    protocol: TCP

  # This is a headless service, Kubernetes won't assign a VIP for it.
  # *.dind.default.svc.cluster.local
  clusterIP: None
  selector:
    app: dind

`

	templatesMap["role-binding.re.yaml"] = `kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .AppName }}
  namespace: {{ .Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .AppName }}
  namespace: {{ .Namespace }}
roleRef:
  kind: Role
  name: {{ .AppName }}
  apiGroup: rbac.authorization.k8s.io`

	templatesMap["role.k8sagent.yaml"] = `{{- if .Values.rbacEnabled }}
{{- if .Values.useNamespaceWideRole }}
kind: Role
{{- else }}
kind: ClusterRole
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name  | quote }}-cluster-reader
  namespace: {{ .Namespace }}
  labels:
    app: {{ .Release.Name  | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
    version: {{ .Values.imageTag | quote }}
rules:
- apiGroups:
  - ""
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
    - ""
  resources: ["pods"]
  verbs:
    - get
    - list
    - watch
    - create
    - deletecollection
- apiGroups:
  - extensions
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
{{- end }}
`

	templatesMap["role.re.yaml"] = `kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .AppName }}
  namespace: {{ .Namespace }}
rules:
- apiGroups: [""]
  resources: ["pods", "persistentvolumeclaims"]
  verbs: ["get", "create", "delete"]
`

	templatesMap["rolebinding.k8sagent.yaml"] = `{{- if .Values.rbacEnabled }}
{{- if .Values.useNamespaceWideRole }}
kind: RoleBinding
{{- else }}
kind: ClusterRoleBinding
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Chart.Name }}-cluster-reader
  namespace: {{ .Namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
    version: {{ .Values.imageTag | quote }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ .Chart.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  {{- if .Values.useNamespaceWideRole }}
  kind: Role
  {{- else }}
  kind: ClusterRole
  {{- end }}
  name: {{ .Chart.Name }}-cluster-reader
{{- end }}
`

	templatesMap["rollback-role-binding.k8sagent.yaml"] = `{{- if .Values.rbacEnabled }}
{{- if .Values.useNamespaceWideRole }}
kind: RoleBinding
{{- else }}
kind: ClusterRoleBinding
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Chart.Name }}-rollback
  namespace: {{ .Namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
    version: {{ .Values.imageTag | quote }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ .Chart.Name }}-rollback
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
  {{- end }}
`

	templatesMap["rollback-serviceaccount.k8sagent.yaml"] = `{{- if and .Values.rbacEnabled (not .Values.useNamespaceWideRole) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}-rollback
  namespace: {{ .Namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
    version: {{ .Values.imageTag | quote }}
{{- end }}
`

	templatesMap["secret.dind-volume-provisioner.vp.yaml"] = `apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: dind-volume-provisioner-{{ .AppName }}
  namespace: {{ .Namespace }}
  labels:
    app: dind-volume-provisioner
data:
{{- if .Storage.GoogleServiceAccount }}
  google-service-account.json: {{ .Storage.GoogleServiceAccount | b64enc }}
{{- end }}
{{- if .Storage.AwsAccessKeyId }}
  aws_access_key_id: {{ .Storage.AwsAccessKeyId | b64enc }}
{{- end }}
{{- if .Storage.AwsSecretAccessKey }}
  aws_secret_access_key: {{ .Storage.AwsSecretAccessKey | b64enc }}
{{- end }}`

	templatesMap["secret.runtime-attach.yaml"] = `apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .AppName }}conf
  namespace: {{ .Namespace }}
data:
{{ range $key, $value := .venonaConf }}
  {{ $key }}: {{ $value }}
{{ end }}`

	templatesMap["secret.venona.yaml"] = `apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .AppName }}
  namespace: {{ .Namespace }}
data:
  codefresh.token: {{ .AgentToken }}`

	templatesMap["service-account.dind-volume-provisioner.vp.yaml"] = `---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: volume-provisioner-{{ .AppName }}
  namespace: {{ .Namespace }}
  labels:
    app: dind-volume-provisioner
`

	templatesMap["service-account.engine.yaml"] = `apiVersion: v1
kind: ServiceAccount
metadata:
  name: engine
  namespace: {{ .Namespace }}`

	templatesMap["service-account.k8sagent.yaml"] = `{{- if .Values.rbacEnabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name  | quote }}
  namespace: {{ .Namespace }}
  labels:
    app: {{ .Release.Name  | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
    version: {{ .Values.imageTag | quote }}
{{- end }}
`

	templatesMap["service-account.re.yaml"] = `apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .AppName }}
  namespace: {{ .Namespace }}`

	templatesMap["service.k8sagent.yaml"] = `apiVersion: v1
kind: Service
metadata:
  name: {{ .AppName }}
  namespace: {{ .Namespace }}
  labels:
    app: {{ .AppName }}
    version: {{ .Version }}
spec:
  type: ClusterIP
  ports:
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: 9020
  selector:
    app: {{ .AppName }}
`

	templatesMap["storageclass.dind-volume-provisioner.vp.yaml"] = `---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Storage.StorageClassName }}
  labels:
    app: dind-volume-provisioner
provisioner: codefresh.io/dind-volume-provisioner-{{ .AppName }}-{{ .Namespace }}
parameters:
{{- if eq .Storage.Backend "local" }}
  volumeBackend: local
  volumeParentDir: {{ .Storage.LocalVolumeParentDir | default "/var/lib/codefresh/dind-volumes" }}
{{- else if eq .Storage.Backend "gcedisk" }}
  volumeBackend: {{ .Storage.Backend }}
  #  pd-ssd or pd-standard
  type: {{ .Storage.VolumeType | default "pd-ssd" }}
  # Valid zone in GCP
  zone: {{ .Storage.AvailabilityZone }}
  # ext4 or xfs (default to ext4 because xfs is not installed on GKE by default )
  fsType: {{ .Storage.FsType | default "ext4" }}
{{- else if or (eq .Storage.Backend "ebs") (eq .Storage.Backend "ebs-csi")}}
  # ebs or ebs-csi
  volumeBackend: {{ .Storage.Backend }}
  #  gp2 or io1
  VolumeType: {{ .Storage.VolumeType | default "gp2" }}
  # Valid zone in aws (us-east-1c, ...)
  AvailabilityZone: {{ .Storage.AvailabilityZone }}
  # ext4 or xfs (default to ext4 )
  fsType: {{ .Storage.FsType | default "ext4" }}
{{- end }}`

	templatesMap["venonaconf.secret.venona.yaml"] = `apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .AppName }}conf
  namespace: {{ .Namespace }}
data:
{{ range $key, $value := .venonaConf }}
  {{ $key }}: {{ $value }}
{{ end }}`

	return templatesMap
}
