env:
  node: true
  commonjs: true
  es6: true
extends: 
  - 'eslint:recommended'
  - 'plugin:jest/recommended'
plugins:
  - jest
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  "jest/no-disabled-tests": "warn"
  "jest/no-focused-tests": "error"
  "jest/no-identical-title": "error"
  "jest/prefer-to-have-length": "warn"
  "jest/valid-expect": "error"
