{{- $runnerContext := deepCopy . }}
{{- $_ := set $runnerContext "Values" (get .Values "runner") }}
{{- $_ := set $runnerContext.Values "global" (get .Values "global") }}

{{- if and $runnerContext.Values.enabled (not (or $runnerContext.Values.global.existingAgentToken $runnerContext.Values.global.agentTokenSecretKeyRef)) .Values.runtime.agent }}
{{- include "runner.resources.secret" $runnerContext }}
{{- end }}
