{{ $cfCommonTplSemver := printf "cf-common-%s" (index .Subcharts "cf-common").Chart.Version }}
{{ $values := .Values.runtime.patch }}
{{- if $values.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "runtime.fullname" . }}-patch
  labels:
    {{- include "runtime.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "5"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    {{- with $values.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with $values.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ . }}
  {{- end }}
  {{- with $values.backoffLimit }}
  backoffLimit: {{ . | int }}
  {{- end }}
  template:
    metadata:
      name: {{ include "runtime.fullname" . }}-patch
      labels:
        {{- include "runtime.labels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml $values.podSecurityContext | nindent 8 }}
      containers:
      - name: patch-runtime
        image: {{ include (printf "%s.image.name" $cfCommonTplSemver ) (dict "image" $values.image "context" .) }}
        imagePullPolicy: {{ $values.image.pullPolicy | default "Always" }}
        command:
        - "/bin/bash"
        args:
        - -ec
        - |
          {{ .Files.Get "files/patch-runtime.sh" | nindent 10 }}
        env:
        - name: API_KEY
          {{- include "runtime.installation-token-env-var-value" . | indent 10}}
        - name: API_HOST
          value: {{ include "runtime.runtime-environment-spec.codefresh-host" . }}
        - name: AGENT
          value: {{  .Values.runtime.agent | quote }}
          {{- include (printf "%s.env-vars" $cfCommonTplSemver) (dict "Values" $values.env "context" .) | nindent 8 }}
        volumeMounts:
        - name: runtime-config
          mountPath: /opt/codefresh/runtime.yaml
          subPath: runtime.yaml
        {{- range $runtimeIndex, $runtimeItem := .Values.extraRuntimes }}
        - name: {{ printf "%s-runtime-config" ( trimPrefix "system/" $runtimeItem.runtimeName | replace "_" "-" ) }}
          mountPath: /opt/codefresh/runtime.d/system/{{ printf "%s.yaml" ( trimPrefix "system/" $runtimeItem.runtimeName) }}
          subPath: {{ printf "%s.yaml" ( trimPrefix "system/" $runtimeItem.runtimeName) }}
        {{- end }}
      {{- with $values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      volumes:
      - name: runtime-config
        configMap:
          name: {{ include "runtime.fullname" . }}-spec
      {{- range $runtimeIndex, $runtimeItem := .Values.extraRuntimes }}
      - name: {{ printf "%s-runtime-config" ( trimPrefix "system/" $runtimeItem.runtimeName | replace "_" "-" ) }}
        configMap:
            name: {{ printf "%s-runtime-config" ( trimPrefix "system/" $runtimeItem.runtimeName | replace "_" "-" ) }}
      {{- end }}
      restartPolicy: OnFailure
{{- end }}
