{{- if .Values.volumeProvisioner.enabled }}
{{ $cfCommonTplSemver := printf "cf-common-%s" (index .Subcharts "cf-common").Chart.Version }}
{{ $values := index .Values.volumeProvisioner "dind-lv-monitor" }}
{{ $localVolumeParentDir := .Values.storage.local.volumeParentDir  }}
{{- if eq .Values.storage.backend "local" }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "dind-lv-monitor.fullname" . }}
  labels:
    {{- include "dind-lv-monitor.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "dind-lv-monitor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dind-lv-monitor.selectorLabels" . | nindent 8 }}
      {{- with $values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include (printf "%s.image.pullSecrets" $cfCommonTplSemver ) . | nindent 8 }}
      serviceAccountName: {{ include "dind-volume-provisioner.serviceAccountName" . }}
      {{- if $values.podSecurityContext.enabled }}
      securityContext: {{- omit $values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if $values.volumePermissions.enabled }}
      initContainers:
      - name: volume-permissions
        image: {{ include (printf "%s.image.name" $cfCommonTplSemver ) (dict "image" $values.volumePermissions.image "context" .) }}
        imagePullPolicy: {{ $values.volumePermissions.image.pullPolicy | default "Always" }}
        command:
         - /bin/sh
        args:
         - -ec
         - |
           chown -R {{ $values.podSecurityContext.runAsUser }}:{{ $values.podSecurityContext.fsGroup }} {{ $localVolumeParentDir }}
        volumeMounts:
        - mountPath: {{ $localVolumeParentDir }}
          name: dind-volume-dir
        {{- if eq ( toString ( $values.volumePermissions.securityContext.runAsUser )) "auto" }}
        securityContext: {{- omit $values.volumePermissions.securityContext "runAsUser" | toYaml | nindent 10 }}
        {{- else }}
        securityContext: {{- $values.volumePermissions.securityContext | toYaml | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml $values.volumePermissions.resources | nindent 10 }}
      {{- end }}
      containers:
      - name: dind-lv-monitor
        image: {{ include (printf "%s.image.name" $cfCommonTplSemver ) (dict "image" $values.image "context" .) }}
        imagePullPolicy: {{ $values.image.pullPolicy | default "Always" }}
        {{- if $values.containerSecurityContext.enabled }}
        securityContext: {{- omit $values.containerSecurityContext "enabled" | toYaml | nindent 10 }}
        {{- end }}
        command:
          - /home/dind-volume-utils/bin/local-volumes-agent
        env:
          {{- include (printf "%s.env-vars" $cfCommonTplSemver) (dict "Values" $values.env "context" .) | nindent 10 }}
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: VOLUME_PARENT_DIR
            value: {{ $localVolumeParentDir }}
        resources:
          {{- toYaml $values.resources | nindent 10  }}
        volumeMounts:
        - mountPath: {{ $localVolumeParentDir }}
          readOnly: false
          name: dind-volume-dir
        {{- with $values.extraVolumeMounts }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with $values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      volumes:
      - name: dind-volume-dir
        hostPath:
          path: {{ $localVolumeParentDir }}
      {{- with $values.extraVolumes }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}
{{- end }}