apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cf-vp.provisionerName" . }}
  labels: {{- include "cf-vp.provisionerLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "cf-vp.provisionerSelectorLabels" . | nindent 6 }}
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels: {{- include "cf-vp.provisionerLabels" . | nindent 9 }}
    spec:
      {{/*      {{ if .Values.VolumeProvisioner.NodeSelector }}*/}}
      {{/*      nodeSelector:*/}}
      {{/*{{ .Storage.VolumeProvisioner.NodeSelector | nodeSelectorParamToYaml | indent 8 | unescape}}*/}}
      {{/*      {{ end }}*/}}
      serviceAccountName: {{ include "cf-vp.fullname" . }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}      
      {{/*      {{ toYaml .Values.tolerations | indent 8 | unescape}}*/}}
      containers:
        - name: dind-volume-provisioner
          {{/*          resources: {{ toYaml .Values.volumeProvisioner.resources | nindent 10 }}*/}}
          image: {{ .Values.volumeProvisioner.image }}
          imagePullPolicy: Always
          command:
            - /usr/local/bin/dind-volume-provisioner
            - -v=4
            - --resync-period=50s
          env:
            {{/*            {{- if $.EnvVars }}*/}}
            {{/*            {{- range $key, $value := $.EnvVars }}*/}}
            {{/*            - name: {{ $key }}*/}}
            {{/*              value: "{{ $value}}"*/}}
            {{/*            {{- end}}*/}}
            {{/*            {{- end}}*/}}
            - name: PROVISIONER_NAME
              value: {{ include "cf-vp.volumeProvisionerName" . }}

            {{- if ne .Values.dockerRegistry "" }}
            - name: DOCKER_REGISTRY
              value: {{ .Values.dockerRegistry }}
            {{- end }}
            {{- if .Values.volumeProvisioner.createDindVolDirResouces.limits }}
            {{- if .Values.volumeProvisioner.createDindVolDirResouces.limits.cpu }}
            - name: CREATE_DIND_LIMIT_CPU
              value: {{ .Values.volumeProvisioner.createDindVolDirResouces.limits.cpu  }}
            {{- end }}
            {{- if .Values.volumeProvisioner.createDindVolDirResouces.limits.memory  }}
            - name: CREATE_DIND_LIMIT_MEMORY
              value: {{ .Values.volumeProvisioner.createDindVolDirResouces.limits.memory   }}
            {{- end }}
            {{- end }}
            {{- if .Values.volumeProvisioner.createDindVolDirResouces.requests }}
            {{- if .Values.volumeProvisioner.createDindVolDirResouces.requests.cpu }}
            - name: CREATE_DIND_REQUESTS_CPU
              value: {{ .Values.volumeProvisioner.createDindVolDirResouces.requests.cpu  }}
            {{- end }}
            {{- if .Values.volumeProvisioner.createDindVolDirResouces.requests.memory }}
            - name: CREATE_DIND_REQUESTS_MEMORY
              value: {{ .Values.volumeProvisioner.createDindVolDirResouces.requests.memory  }}
            {{- end }}
            {{- end }}
            {{- if .Values.storage.ebs.accessKeyId }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: dind-volume-provisioner
                  key: aws_access_key_id
            {{- end }}
            {{- if .Values.storage.ebs.secretAccessKey }}
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: dind-volume-provisioner
                  key: aws_secret_access_key
            {{- end }}
            {{- if .Values.storage.gce.serviceAccountJson }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/dind-volume-provisioner/credentials/google-service-account.json
            {{- end }}
            {{- if .Values.volumeProvisioner.mountAzureJson }}
            - name: AZURE_CREDENTIAL_FILE
              value: "/etc/kubernetes/azure.json"
          {{- end }}
          volumeMounts:
            {{- if .Values.volumeProvisioner.mountAzureJson }}
            - name: azure-json
              readOnly: true
              mountPath: "/etc/kubernetes/azure.json"
            {{- end }}
            {{- if .Values.storage.gce.serviceAccountJson }}
            - name: credentials
              readOnly: true
              mountPath: "/etc/dind-volume-provisioner/credentials"
      {{- end }}
      volumes:
        {{- if .Values.volumeProvisioner.mountAzureJson }}
        - name: azure-json
          hostPath:
            path: /etc/kubernetes/azure.json
            type: File
        {{- end }}
        {{- if .Values.storage.gce.serviceAccountJson }}
        - name: credentials
          secret:
            secretName: dind-volume-provisioner
  {{- end }}
