{{ $cfCommonTplSemver := printf "cf-common-%s" (index .Subcharts "cf-common").Chart.Version }}
{{ $values := .Values.volumeProvisioner }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dind-volume-provisioner.fullname" . }}
  labels:
    {{- include "dind-volume-provisioner.labels" . | nindent 4 }}
spec:
  replicas: {{ $values.replicasCount }}
  strategy:
    type: {{ $values.updateStrategy.type }}
  selector:
    matchLabels:
      {{- include "dind-volume-provisioner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dind-volume-provisioner.selectorLabels" . | nindent 8 }}
      {{- with $values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include (printf "%s.image.pullSecrets" $cfCommonTplSemver ) . | nindent 8 }}
      serviceAccountName: {{ include "dind-volume-provisioner.serviceAccountName" . }}
      {{- if $values.podSecurityContext.enabled }}
      securityContext: {{- omit $values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      containers:
      - name: dind-volume-provisioner
        image: {{ include (printf "%s.image.name" $cfCommonTplSemver ) (dict "image" $values.image "context" .) }}
        imagePullPolicy: {{ $values.image.pullPolicy | default "Always" }}
        command:
          - /usr/local/bin/dind-volume-provisioner
          - -v=4
          - --resync-period=50s
        env:
        {{- include "dind-volume-provisioner.environment-variables" . | nindent 8 }}
        resources:
          {{- toYaml $values.resources | nindent 12  }}
        volumeMounts:
        {{- include "dind-volume-provisioner.volumeMounts.calculated" . | nindent 8 }}
        {{- with $values.extraVolumeMounts }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with $values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      volumes:
      {{- include "dind-volume-provisioner.volumes.calculated" . | nindent 6 }}
      {{- with $values.extraVolumes }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
