{{- if .Values.volumeProvisioner.enabled }}
{{ $values := .Values.storage }}
---
{{- if or $values.ebs.accessKeyId $values.ebs.secretAccessKey $values.gcedisk.serviceAccountJson  }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "dind-volume-provisioner.fullname" . }}
  labels:
    {{- include "dind-volume-provisioner.labels" . | nindent 4 }}
data:
  {{- with $values.gcedisk.serviceAccountJson }}
  google-service-account.json: {{ .| b64enc }}
  {{- end }}
  {{- with $values.ebs.accessKeyId }}
  aws_access_key_id: {{ . | b64enc }}
  {{- end }}
  {{- with $values.ebs.secretAccessKey }}
  aws_secret_access_key: {{ . | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
