{{- define "runner-init.environment-variables.defaults" }}
HOME: /tmp
{{- end }}

{{- define "runner-init.environment-variables.calculated" }}
AGENT_NAME: {{ .Values.global.agentName }}
API_HOST: {{ .Values.global.codefreshHost }}
AGENT_CODEFRESH_TOKEN:
  valueFrom:
    secretKeyRef:
      name: {{ include "runner.fullname" . }}
      key: agent-codefresh-token
      optional: true
CONFIG_MAP_NAME: {{ include "monitor.fullname" . }}
KUBE_CONTEXT: {{ .Values.global.context }}
KUBE_NAMESPACE: {{ .Release.Namespace }}
OWNER_NAME: {{ include "runner.fullname" . }}
RUNTIME_NAME: {{ .Values.global.runtimeName }}
SECRET_NAME: {{ include "runner.fullname" . }}
USER_CODEFRESH_TOKEN:
  valueFrom:
    secretKeyRef:
      name: {{ include "monitor.fullname" . }}
      key: codefresh.token
      optional: true
{{- end }}

{{- define "runner-init.environment-variables" }}
  {{- $cfCommonTplSemver := printf "cf-common-%s" (index .Subcharts "cf-common").Chart.Version }}
  {{- $defaults := (include "runner-init.environment-variables.defaults" . | fromYaml) }}
  {{- $calculated := (include "runner-init.environment-variables.calculated" . | fromYaml) }}
  {{- $overrides := .Values.env }}
  {{- $mergedValues := mergeOverwrite (merge $defaults $calculated) $overrides }}
  {{- include (printf "%s.env-vars" $cfCommonTplSemver) (dict "Values" $mergedValues "context" .) }}
{{- end }}
