apiVersion: v2
description: A Helm chart for Codefresh Runner
name: cf-runtime
version: 1.0.1
home: https://github.com/codefresh-io/venona
keywords:
  - codefresh
  - runner
maintainers:
  - name: codefresh
    url: https://codefresh-io.github.io/
