apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "runtime.dind-daemon-configmap-name" . }}
  labels:
    {{- include "runtime.labels" . | nindent 4 }}
data:
  daemon.json: |
{{ coalesce .Values.re.dindDaemon .Values.runtime.dindDaemon | toPrettyJson | indent 4 }}
