{{- $dindContext := deepCopy . }}
{{- $_ := set $dindContext.Values "dindDaemon" (get .Values.runtime "dindDaemon") }}
{{- $_ := set $dindContext.Values "nameOverride" (get .Values "nameOverride") }}
{{- $_ := set $dindContext.Values "fullnameOverride" (get .Values "fullnameOverride") }}

{{- include "runtime.dind.configmap" $dindContext }}
