{{ $values := .Values.runtime }}
---
{{- if or $values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "runtime.engine-service-account-name" . }}
  labels:
    {{- include "runtime.labels" . | nindent 4 }}
  {{- with $values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if $values.rbac.create }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "runtime.engine-service-account-name" . }}
  labels:
    {{- include "runner.labels" . | nindent 4 }}
rules:
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get" ]
{{- with $values.rbac.rules }}
  {{ toYaml . | nindent 2 }}
{{- end }}
{{- end }}
---
{{- if and $values.serviceAccount.create $values.rbac.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "runtime.engine-service-account-name" . }}
  labels:
    {{- include "runner.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "runtime.engine-service-account-name" . }}
roleRef:
  kind: Role
  name: {{ include "runtime.engine-service-account-name" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
