{{- if and .Values.global.codefreshToken }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "runtime.installation-token-secret-name" . }}
  labels:
    {{- include "runtime.labels" . | nindent 4 }}
data:
  codefresh-api-token: {{ .Values.global.codefreshToken | b64enc }}
{{- end }}