{{- if .Values.runtime.agent }}
{{- if or (not .Values.global.existingDindCertsSecret ) (not .Values.global.dindCertsSecretRef) }}
apiVersion: v1
type: Opaque
kind: Secret
metadata:
  {{/* has to be a constant */}}
  name: codefresh-certs-server
  labels:
    {{- include "runtime.labels" . | nindent 4 }}
data:
  server-cert.pem: {{ .Values.global.keys.serverCert | b64enc }}
  server-key.pem: {{ .Values.global.keys.key | b64enc }}
  ca.pem: {{ .Values.global.keys.ca | b64enc }}
{{- end }}
{{- end }}