{{- if and .Values.global.codefresh.userToken.token }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "runtime.installation-token-secret-name" . }}
  labels:
    {{- include "runtime.labels" . | nindent 4 }}
data:
  codefresh-api-token: {{ .Values.global.codefresh.userToken.token | b64enc }}
{{- end }}