{{ $values := .Values.monitor }}
{{- if and $values.enabled }}
---
{{- if $values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "monitor.serviceAccountName" . }}
  labels:
    {{- include "monitor.labels" . | nindent 4 }}
  {{- with $values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if $values.rbac.create }}
kind: {{ $values.rbac.namespaced | ternary "Role" "ClusterRole" }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "monitor.fullname" . }}
  labels:
    {{- include "monitor.labels" . | nindent 4 }}
rules:
  - apiGroups: [ "" ]
    resources: [ "*" ]
    verbs: [ "get", "list", "watch", "create", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "list", "watch", "create", "deletecollection" ]
  - apiGroups: [ "extensions" ]
    resources: [ "*" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "apps" ]
    resources: [ "*" ]
    verbs: [ "get", "list", "watch" ]
{{- with $values.rbac.rules }}
  {{ toYaml . | nindent 2 }}
{{- end }}
{{- end }}
---
{{- if and $values.serviceAccount.create $values.rbac.create }}
kind: {{ $values.rbac.namespaced | ternary "RoleBinding" "ClusterRoleBinding" }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "monitor.fullname" . }}
  labels:
    {{- include "monitor.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "monitor.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "monitor.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
