{{- define "dind-volume-provisioner.resources.secret" -}}
{{- if or .Values.storage.ebs.accessKeyId .Values.storage.ebs.secretAccessKey .Values.storage.gcedisk.serviceAccountJson }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "dind-volume-provisioner.fullname" . }}
  labels:
    {{- include "dind-volume-provisioner.labels" . | nindent 4 }}
data:
  {{- with .Values.storage.gcedisk.serviceAccountJson }}
  google-service-account.json: {{ .| b64enc }}
  {{- end }}
  {{- with .Values.storage.ebs.accessKeyId }}
  aws_access_key_id: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.storage.ebs.secretAccessKey }}
  aws_secret_access_key: {{ . | b64enc }}
  {{- end }}
{{- end }}
{{- end -}}
