before:
  hooks:
    - go mod tidy

builds:
- 
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - 386
  env:
  - CGO_ENABLED=0
  ldflags:
  - -X github.com/codefresh-io/venona/venonactl/cmd.version={{.Version}} -X github.com/codefresh-io/venona/venonactl/cmd.commit={{.Commit}} -X github.com/codefresh-io/venona/venonactl/cmd.date={{.Date}}

archives:
- 
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  format_overrides:
  - goos: windows
    format: zip
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'


release:
  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-rc1
  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: true
