{{- define "event-exporter.resources.serviceMonitor" -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "event-exporter.fullname" . }}
  labels:
    {{- include "event-exporter.labels" . | nindent 4 }}
spec:
  endpoints:
  - port: metrics
  selector:
    {{- include "event-exporter.selectorLabels" . | nindent 4 }}
{{- end -}}