{{ $cfCommonTplSemver := printf "cf-common-%s" (index .Subcharts "cf-common").Chart.Version }}
{{ $values := .Values.appProxy }}
{{- if $values.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-proxy.fullname" . }}
  labels:
    {{- include "app-proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ $values.replicasCount }}
  strategy:
    type: {{ $values.updateStrategy.type }}
  selector:
    matchLabels:
      {{- include "app-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app-proxy.selectorLabels" . | nindent 8 }}
      {{- with $values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include (printf "%s.image.pullSecrets" $cfCommonTplSemver ) . | nindent 8 }}
      serviceAccountName: {{ include "app-proxy.serviceAccountName" . }}
      {{- if $values.podSecurityContext.enabled }}
      securityContext: {{- omit $values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      containers:
      - name: app-proxy
        image: {{ include (printf "%s.image.name" $cfCommonTplSemver ) (dict "image" $values.image "context" .) }}
        imagePullPolicy: {{ $values.image.pullPolicy | default "Always" }}
        env:
        {{- include "app-proxy.environment-variables" . | nindent 8 }}
        ports:
        - name: http
          containerPort: 3000
        readinessProbe:
          initialDelaySeconds: {{ $values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ $values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ $values.readinessProbe.timeoutSeconds }}
          successThreshold: {{ $values.readinessProbe.successThreshold }}
          failureThreshold: {{ $values.readinessProbe.failureThreshold }}
          httpGet:
            path: /health
            port: http
        resources:
          {{- toYaml $values.resources | nindent 12  }}
        volumeMounts:
        {{- with $values.extraVolumeMounts }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with $values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      volumes:
      {{- with $values.extraVolumes }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}