{{ $values := .Values.appProxy }}
{{- if $values.enabled }}
---
{{- if $values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app-proxy.serviceAccountName" . }}
  labels:
    {{- include "app-proxy.labels" . | nindent 4 }}
  {{- with $values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if $values.rbac.create }}
kind: {{ $values.rbac.namespaced | ternary "Role" "ClusterRole" }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "app-proxy.fullname" . }}
  labels:
    {{- include "app-proxy.labels" . | nindent 4 }}
rules:
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get" ]
{{- with $values.rbac.rules }}
  {{ toYaml . | nindent 2 }}
{{- end }}
{{- end }}
---
{{- if and $values.serviceAccount.create $values.rbac.create }}
kind: {{ $values.rbac.namespaced | ternary "RoleBinding" "ClusterRoleBinding" }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "app-proxy.fullname" . }}
  labels:
    {{- include "app-proxy.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "app-proxy.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "app-proxy.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
