{{- if .Values.appProxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-proxy.fullname" . }}
  labels:
    {{- include "app-proxy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    {{- include "app-proxy.selectorLabels" . | nindent 4 }}
{{- end }}