{{ $cfCommonTplSemver := printf "cf-common-%s" (index .Subcharts "cf-common").Chart.Version }}
{{ $values := .Values.runtime.patch }}
{{- if $values.enabled }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "runtime.fullname" . }}-spec
  labels:
    {{- include "runtime.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
    {{- with $values.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  runtime.yaml: |-
    {{ include "runtime.runtime-environment-spec.template" . | nindent 4 }}
{{- end }}
