{{ $cfCommonTplSemver := printf "cf-common-%s" (index .Subcharts "cf-common").Chart.Version }}
{{ $values := .Values.runtime.patch }}
{{- if $values.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "runtime.fullname" . }}-delete
  labels:
    {{- include "runtime.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    {{- with $values.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with $values.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ . }}
  {{- end }}
  {{- with $values.backoffLimit }}
  backoffLimit: {{ . | int }}
  {{- end }}
  template:
    metadata:
      name: {{ include "runtime.fullname" . }}-delete
      labels:
        {{- include "runtime.labels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml $values.podSecurityContext | nindent 8 }}
      containers:
      - name: delete-runtime
        image: {{ include (printf "%s.image.name" $cfCommonTplSemver ) (dict "image" $values.image "context" .) }}
        imagePullPolicy: {{ $values.image.pullPolicy | default "Always" }}
        command:
        - "/bin/bash"
        args:
        - -ec
        - |
          codefresh auth create-context --api-key $API_KEY --url $API_HOST
{{- if .Values.runtime.agent }}
          exit 0  # TO-DO
{{- else }}
          codefresh delete sys-re {{ .Values.global.runtimeName }} || true
{{- end }}
        env:
        - name: API_KEY
          {{- include "runtime.installation-token-env-var-value" . | indent 10}}
        - name: API_HOST
          value: {{ include "runtime.runtime-environment-spec.codefresh-host" . }}
          {{- include (printf "%s.env-vars" $cfCommonTplSemver) (dict "Values" $values.env "context" .) | nindent 8 }}
      {{- with $values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      restartPolicy: OnFailure
{{- end }}
