
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at 2018-12-29 12:01:41.685174387 +0200 IST m=+0.000667660
// using data from templates/kubernetes_dind
package kubernetes_dind

func TemplatesMap() map[string]string {
    templatesMap := make(map[string]string)

templatesMap["codefresh-certs-server-secret.yaml"] = `apiVersion: v1
type: Opaque
kind: Secret
metadata:
  labels:
    app: isserctl
  name: codefresh-certs-server
data:
  server-cert.pem: {{ .ServerCert.Cert | base64.Encode  }}
  server-key.pem: {{ .ServerCert.Key | base64.Encode  }}
  ca.pem: {{ .ServerCert.Ca | base64.Encode  }}

` 

templatesMap["dind-daemon-conf.yml"] = `---
apiVersion: v1
kind: ConfigMap
metadata:
  name: codefresh-dind-config
data:
  daemon.json: |
    {
      "hosts": [ "unix:///var/run/docker.sock",
                 "unix:///var/run/codefresh/docker.sock",
                 "tcp://0.0.0.0:1300"],
      "storage-driver": "overlay",
      "storage-opts": ["overlay.override_kernel_check=1"],
      "tlsverify": true,  
      "tls": true,
      "tlscacert": "/etc/ssl/cf-client/ca.pem",
      "tlscert": "/etc/ssl/cf/server-cert.pem",
      "tlskey": "/etc/ssl/cf/server-key.pem",
      "insecure-registries" : ["192.168.99.100:5000"],
      "metrics-addr" : "0.0.0.0:9323",
      "experimental" : true
    }
` 

templatesMap["dind-headless-service.yml"] = `---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dind
  name: dind
spec:
  ports:
  - name: "dind-port"
    port: 1300
    protocol: TCP

  # This is a headless service, Kubernetes won't assign a VIP for it.
  # *.dind.default.svc.cluster.local
  clusterIP: None
  selector:
    app: dind

` 

    return  templatesMap
}
