# Values used in `helm-chart-ci` pipeline
# All placeholders will be set during ci build
fullnameOverride: cf-runtime-override
global:
  codefreshToken: placeholder
  accountId: placeholder
  context: placeholder
  # intentionally empty
  runtimeName: ""
  agentName: ""
appProxy:
  enabled: true
  ingress:
    class: nginx
    host: placeholder
    pathPrefix: /app-proxy
monitor:
  enabled: true
  rbac:
    namespaced: true
runtime:
  dind:
    podLabels:
      key: dind
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
    limits:
        cpu: 1000m
        memory: 1024Mi
  engine:
    podLabels:
      key: engine
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
    limits:
        cpu: 1000m
        memory: 1024Mi
