volumeProvisioner:
  env:
    IS_ROOTLESS: true
  dind-lv-monitor:
    image:
      tag: 1.30.9-rootless
      digest: sha256:e231e5d5b75424c8580f6e2922db9b1d462df2883435fb92fce9dee36503f52f
    containerSecurityContext:
      runAsUser: 1000
    podSecurityContext:
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"
    volumePermissions:
      enabled: true
runtime:
  dind:
    image:
      tag: 3.0.22-rootless
      digest: sha256:ae52f768273881cef45638d577ffd565fb62fdc5b5d7f713b3be2c63be147537
    userVolumeMounts:
      dind:
        name: dind
        mountPath: /home/rootless/.local/share/docker
    containerSecurityContext:
      privileged: true
      runAsUser: 1000
    podSecurityContext:
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"
    volumePermissions:
      enabled: true
