# Values used in `helm-chart-ci` pipeline
codefresh:
  userToken:
    token: placeholder
    secretKeyRef: {}
appProxy:
  enabled: true
  ingress:
    class: nginx
    host: placeholder
    pathPrefix: /app-proxy
monitor:
  enabled: true
  rbac:
    namespaced: true
runner: {}
