# Values used in `helm-chart-ci` pipeline
# All placeholders will be set during ci build
global:
  codefreshToken: placeholder
  accountId: placeholder
  agentName: placeholder
  context: placeholder
  # intentionally empty
  runtimeName: ""
appProxy:
  enabled: true
  ingress:
    class: nginx
    host: placeholder
    pathPrefix: /app-proxy
monitor:
  enabled: true
  rbac:
    namespaced: true
runner:
  # TO-DO: remove once https://github.com/codefresh-io/cli/pull/833 is merged
  init:
    image:
      tag: CR-16346-venona-helm-rootless
runtime:
  dind:
    image:
      tag: 20.10.24-1.27.0-rootless
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
    limits:
        cpu: 1000m
        memory: 1024Mi
    # podAnnotations:
    #   karpenter.sh/do-not-evict: 'true'
    # nodeSelector:
    #   node-type: dind
    # tolerations:
    # - effect: NoSchedule
    #   key: codefresh.io
    #   operator: Equal
    #   value: dinds
  engine:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
    limits:
        cpu: 1000m
        memory: 1024Mi
    # podAnnotations:
    #   karpenter.sh/do-not-evict: 'true'
    # nodeSelector:
    #   node-type: engine
    # tolerations:
    # - effect: NoSchedule
    #   key: codefresh.io
    #   operator: Equal
    #   value: engines