# Values used in `helm-chart-ci` pipeline
global:
  codefreshToken: placeholder
appProxy:
  enabled: true
  ingress:
    class: nginx
    host: placeholder
    pathPrefix: /app-proxy
monitor:
  enabled: true
  rbac:
    namespaced: true
runner: {}
runtime:
  dind:
    image:
      tag: 20.10.24-1.27.0-rootless
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
    limits:
        cpu: 1000m
        memory: 1024Mi
    podAnnotations:
      karpenter.sh/do-not-evict: 'true'
    nodeSelector:
      node-type: dind
    tolerations:
    - effect: NoSchedule
      key: codefresh.io
      operator: Equal
      value: dinds
  engine:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
    limits:
        cpu: 1000m
        memory: 1024Mi
    podAnnotations:
      karpenter.sh/do-not-evict: 'true'
    nodeSelector:
      node-type: engine
    tolerations:
    - effect: NoSchedule
      key: codefresh.io
      operator: Equal
      value: engines