# Values used in `helm-chart-ci` pipeline
appProxy:
  enabled: true
  ingress:
    class: nginx
    host: runner-helm-ci-test.cf-op.com
    pathPrefix: /app-proxy
monitor:
  enabled: true
  rbac:
    namespaced: true
runner: {}
