# Values used in `helm-chart-ci` pipeline
# All placeholders will be set during ci build
global:
  codefreshToken: placeholder
  accountId: placeholder
  context: placeholder
  # intentionally empty
  runtimeName: ""
  agentName: ""
appProxy:
  enabled: true
  ingress:
    class: nginx
    host: placeholder
    pathPrefix: /app-proxy
monitor:
  enabled: true
  rbac:
    namespaced: true
runner:
  sidecar:
    enabled: true
runtime:
  dind:
    image:
      tag: 24.0.6-1.28.2-rootless
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
    limits:
        cpu: 1000m
        memory: 1024Mi
  engine:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
    limits:
        cpu: 1000m
        memory: 1024Mi
