global:
  runtimeName: system/test-ci-runtime

runtime:
  agent: false
  inCluster: false
  description: "Test runtime created by venona-helm-chart-ci pipeline"
  kubeconfigFilePath: /opt/codefresh/kubeconfigs/prod-ue1-runtime-free-1/kubeconfig
  kubeconfigName: prod-ue1-runtime-free-1
  dind:
    pvcs:
      dind:
        storageClassName: dind-ebs-csi-us-east-1a-workflows
  accounts:
    - 5672d8deb6724b6e359adf62 # codefresh-inc

volumeProvisioner:
  enabled: false

monitor:
  enabled: false

appProxy:
  enabled: false
