# Values used in `helm-chart-ci` pipeline
# All placeholders will be set during ci build
global:
  codefreshToken: placeholder
  accountId: placeholder
  context: placeholder
  # intentionally empty
  runtimeName: ""
  agentName: ""
appProxy:
  enabled: true
  ingress:
    class: nginx
    host: placeholder
    pathPrefix: /app-proxy
monitor:
  enabled: true
  rbac:
    namespaced: true
runner:
  sidecar:
    enabled: true
runtime:
  dind:
    image:
      tag: 26.0.0-1.28.6-rootless
    podLabels:
      key: dind
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
    limits:
        cpu: 1000m
        memory: 1024Mi
    env:
      DOCKER_ENABLE_DEPRECATED_PULL_SCHEMA_1_IMAGE: "true"
  engine:
    podLabels:
      key: engine
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
    limits:
        cpu: 1000m
        memory: 1024Mi
