// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Kubernetes is an autogenerated mock type for the Kubernetes type
type Kubernetes struct {
	mock.Mock
}

// CreateResource provides a mock function with given fields: spec
func (_m *Kubernetes) CreateResource(spec string) error {
	ret := _m.Called(spec)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(spec)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteResource provides a mock function with given fields: spec
func (_m *Kubernetes) DeleteResource(spec string) error {
	ret := _m.Called(spec)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(spec)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
