## Reference: https://github.com/amannn/action-semantic-pull-request
name: "PR Lint"

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: false